from __future__ import annotations

from typing import Protocol

from greynoc_detector_engine.models.cve import CVERecord
from greynoc_detector_engine.models.detection import GeneratedDetection
from greynoc_detector_engine.models.kev import KEVRecord
from greynoc_detector_engine.models.scoring import ScoreResult
from greynoc_detector_engine.models.source import SourceItem
from greynoc_detector_engine.models.threat import ThreatRecord


class StorageBackend(Protocol):
    def initialize(self) -> None: ...

    def upsert_raw_item(self, record: SourceItem) -> None: ...

    def list_raw_items(self) -> list[SourceItem]: ...

    def upsert_cve(self, record: CVERecord) -> None: ...

    def list_cves(self) -> list[CVERecord]: ...

    def get_cve(self, cve_id: str) -> CVERecord | None: ...

    def upsert_kev(self, record: KEVRecord) -> None: ...

    def list_kev(self) -> list[KEVRecord]: ...

    def get_kev(self, cve_id: str) -> KEVRecord | None: ...

    def upsert_threat(self, record: ThreatRecord) -> None: ...

    def list_threats(self) -> list[ThreatRecord]: ...

    def get_threat(self, threat_id: str) -> ThreatRecord | None: ...

    def upsert_detection(self, record: GeneratedDetection) -> None: ...

    def list_detections(self) -> list[GeneratedDetection]: ...

    def get_detection(self, detection_id: str) -> GeneratedDetection | None: ...

    def record_source_run(self, source_id: str, status: str, message: str) -> None: ...

    def record_score_event(self, target_id: str, score_type: str, score: ScoreResult) -> None: ...
