from __future__ import annotations

from typing import Protocol

from greynoc_detector_engine.enrich.reputation import IndicatorReputation
from greynoc_detector_engine.models.asset import AssetRecord, TargetLikelihood
from greynoc_detector_engine.models.cve import CVERecord
from greynoc_detector_engine.models.detection import GeneratedDetection
from greynoc_detector_engine.models.feedback import ThreatFeedback
from greynoc_detector_engine.models.job import JobHistoryEntry
from greynoc_detector_engine.models.kev import KEVRecord
from greynoc_detector_engine.models.network import (
    HoneypotEvent,
    ICSObservation,
    IntrusionSignal,
    NetworkDevice,
)
from greynoc_detector_engine.models.prediction import (
    AttackForecast,
    CampaignCluster,
    EPSSScore,
)
from greynoc_detector_engine.models.scoring import ScoreEvent, ScoreResult
from greynoc_detector_engine.models.source import SourceItem, SourceRun
from greynoc_detector_engine.models.threat import ThreatRecord
from greynoc_detector_engine.spacestation.adaptive import HostBaseline


class StorageBackend(Protocol):
    def initialize(self) -> None: ...

    def upsert_raw_item(self, record: SourceItem) -> None: ...

    def list_raw_items(self) -> list[SourceItem]: ...

    def upsert_cve(self, record: CVERecord) -> None: ...

    def list_cves(self) -> list[CVERecord]: ...

    def get_cve(self, cve_id: str) -> CVERecord | None: ...

    def upsert_kev(self, record: KEVRecord) -> None: ...

    def list_kev(self) -> list[KEVRecord]: ...

    def get_kev(self, cve_id: str) -> KEVRecord | None: ...

    def upsert_threat(self, record: ThreatRecord) -> None: ...

    def list_threats(self) -> list[ThreatRecord]: ...

    def get_threat(self, threat_id: str) -> ThreatRecord | None: ...

    def upsert_detection(self, record: GeneratedDetection) -> None: ...

    def list_detections(self) -> list[GeneratedDetection]: ...

    def get_detection(self, detection_id: str) -> GeneratedDetection | None: ...

    def record_source_run(self, run: SourceRun) -> SourceRun: ...

    def list_source_runs(self, limit: int = 100) -> list[SourceRun]: ...

    def record_score_event(self, target_id: str, score_type: str, score: ScoreResult) -> None: ...

    def list_score_events(
        self,
        *,
        target_id: str | None = None,
        score_type: str | None = None,
        limit: int = 100,
    ) -> list[ScoreEvent]: ...

    def upsert_epss(self, score: EPSSScore) -> None: ...

    def list_epss(self) -> list[EPSSScore]: ...

    def get_epss(self, cve_id: str) -> EPSSScore | None: ...

    def upsert_campaign(self, campaign: CampaignCluster) -> None: ...

    def list_campaigns(self) -> list[CampaignCluster]: ...

    def get_campaign(self, campaign_id: str) -> CampaignCluster | None: ...

    def record_attack_forecast(self, threat_id: str, forecast: AttackForecast) -> None: ...

    def list_forecasts_for_threat(self, threat_id: str) -> list[AttackForecast]: ...

    def upsert_indicator_reputation(self, reputation: IndicatorReputation) -> None: ...

    def list_indicator_reputation(self) -> list[IndicatorReputation]: ...

    def upsert_asset(self, asset: AssetRecord) -> None: ...

    def list_assets(self) -> list[AssetRecord]: ...

    def record_target_likelihood(self, likelihood: TargetLikelihood) -> None: ...

    def list_target_likelihoods_for_threat(self, threat_id: str) -> list[TargetLikelihood]: ...

    def upsert_network_device(self, device: NetworkDevice) -> None: ...

    def list_network_devices(self) -> list[NetworkDevice]: ...

    def record_ics_observation(self, observation: ICSObservation) -> None: ...

    def list_ics_observations(self) -> list[ICSObservation]: ...

    def upsert_intrusion_signal(self, signal: IntrusionSignal) -> None: ...

    def list_intrusion_signals(self) -> list[IntrusionSignal]: ...

    def record_honeypot_event(self, event: HoneypotEvent) -> None: ...

    def list_honeypot_events(self) -> list[HoneypotEvent]: ...

    def upsert_threat_feedback(self, feedback: ThreatFeedback) -> None: ...

    def list_threat_feedback(self) -> list[ThreatFeedback]: ...

    def upsert_scan_baseline(self, baseline: HostBaseline) -> None: ...

    def list_scan_baselines(self) -> list[HostBaseline]: ...

    def record_forecast_outcome(
        self,
        *,
        threat_id: str,
        forecast_probability: float,
        forecast_horizon: str,
        verified_attack: bool,
        notes: str = "",
    ) -> None: ...

    def list_forecast_outcomes(self) -> list[dict[str, object]]: ...

    def upsert_job_history(self, entry: JobHistoryEntry) -> None: ...

    def list_job_history(
        self,
        *,
        job_type: str | None = None,
        limit: int = 100,
    ) -> list[JobHistoryEntry]: ...

    def get_job_history(self, job_id: str) -> JobHistoryEntry | None: ...
